server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
    password: root
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    ip-address: 127.0.0.1
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 5
#    prefer-ip-address: true
logging:
  level:
    com:
      leyou:
        dao:
          '*': debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.leyou.dao

